# 错误码常量表
from __future__ import annotations

class ErrorCodes:
    # === 通用 ===
    OK = "OK"
    COMMON_ERROR = "COMMON.ERROR"
    COMMON_INVALID_PARAMS = "COMMON.INVALID_PARAMS"
    COMMON_NOT_FOUND = "COMMON.NOT_FOUND"
    COMMON_METHOD_NOT_ALLOWED = "COMMON.METHOD_NOT_ALLOWED"
    
    # === 认证/权限 ===
    AUTH_UNAUTHORIZED = "AUTH.UNAUTHORIZED"
    AUTH_FORBIDDEN = "AUTH.FORBIDDEN"
    AUTH_INVALID_CREDENTIALS = "AUTH.INVALID_CREDENTIALS"
    AUTH_TOTP_REQUIRED = "AUTH.TOTP_REQUIRED"
    AUTH_TOTP_INVALID = "AUTH.TOTP_INVALID"
    
    # === 幂等相关 ===
    IDEMPOTENCY_KEY_MISSING = "IDEMPOTENCY_KEY_MISSING"
    IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    
    # === 注册 ===
    REGISTER_EMAIL_EXISTS = "REGISTER.EMAIL_EXISTS"
    REGISTER_CODE_INVALID = "REGISTER.CODE_INVALID"
    REGISTER_CODE_EXPIRED = "REGISTER.CODE_EXPIRED"
    REGISTER_CACHE_MISSING = "REGISTER.CACHE_MISSING"
    
    # === 安全/验证码 ===
    SECURITY_TURNSTILE_FAILED = "SECURITY.TURNSTILE_FAILED"
    
    # === 限流 ===
    RATE_LIMIT_TOO_MANY_REQUESTS = "RATE_LIMIT.TOO_MANY_REQUESTS"
    
    # === 系统 ===
    SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
    
    # === 通用 ===
    SUCCESS = "SUCCESS"