# Generated by Django 5.2.2 on 2026-02-02 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigIntegerField(editable=False, help_text='雪花算法生成的用户ID', primary_key=True, serialize=False, verbose_name='用户ID')),
                ('email', models.EmailField(db_index=True, help_text='用于用户账户登录与验证', max_length=254, unique=True, verbose_name='邮箱地址')),
                ('username', models.CharField(db_index=True, default='', help_text='用户名(默认为邮箱地址)', max_length=150, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, help_text='可选添加手机号', max_length=20, null=True, verbose_name='手机号')),
                ('organization', models.BigIntegerField(blank=True, help_text='所属组织/项目', null=True, verbose_name='组织ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户是否启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='后台管理员')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='是否启用TOTP')),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True, verbose_name='TOTP密钥')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='上次登录IP')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已逻辑删除')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录IP')),
                ('login_type', models.CharField(blank=True, help_text='登录方式(如:password/totp/github/email-code等)', max_length=64, null=True, verbose_name='登录方式')),
                ('login_status', models.BooleanField(default=True, verbose_name='当前登录是否成功')),
                ('fail_reason', models.CharField(blank=True, help_text='如密码错误/验证码失效等', max_length=128, null=True, verbose_name='失败原因')),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True, verbose_name='浏览器UA')),
                ('platform', models.CharField(blank=True, help_text='如IOS/Android/Windows等', max_length=64, null=True, verbose_name='设备平台')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='基于IP的地理位置')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('risk_flag', models.BooleanField(default=False, verbose_name='是否为风控标记登录')),
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '用户登录记录',
                'db_table': 'users_login_record',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, help_text='图片URL地址', null=True, verbose_name='头像URL')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个性签名')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='资料更新时间')),
                ('user', models.OneToOneField(help_text='关联的主用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'users_profile',
            },
        ),
    ]
