# Generated by Django 5.2.2 on 2026-05-15 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(editable=False, help_text='(雪花算法生成的用户ID)', primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='', help_text='用户名', max_length=150, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_identifier', models.CharField(blank=True, default='', help_text='管理员ID/邮箱快照，避免外键置空后丢失审计主体', max_length=255, verbose_name='管理员快照')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('password_change', '修改密码'), ('admin_action', '后台动作'), ('force_logout', '强制下线')], max_length=32, verbose_name='操作类型')),
                ('reason', models.CharField(blank=True, default='', max_length=128, verbose_name='操作原因')),
                ('target_model', models.CharField(db_index=True, max_length=128, verbose_name='目标模型')),
                ('target_object_id', models.CharField(db_index=True, max_length=64, verbose_name='目标对象ID')),
                ('target_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='目标对象快照')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='变更字段')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='变更前')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='变更后')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='浏览器UA')),
                ('request_path', models.CharField(blank=True, default='', max_length=512, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, default='', max_length=16, verbose_name='请求方法')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='审计时间')),
                ('actor', models.ForeignKey(blank=True, help_text='执行后台写操作的管理员；用户被删除后保留快照字段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作管理员')),
            ],
            options={
                'verbose_name': 'Admin操作审计日志',
                'verbose_name_plural': 'Admin操作审计日志',
                'db_table': 'users_admin_audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['actor', '-created_at'], name='idx_admin_audit_actor_time'), models.Index(fields=['target_model', 'target_object_id'], name='idx_admin_audit_target'), models.Index(fields=['action', '-created_at'], name='idx_admin_audit_action_time')],
            },
        ),
    ]
