# Generated by Django 5.2.2 on 2025-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined_time',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='userloginrecord',
            name='fail_reason',
            field=models.CharField(blank=True, help_text='如密码错误/验证码失效等', max_length=128, null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='userloginrecord',
            name='login_status',
            field=models.BooleanField(default=True, verbose_name='当前登录是否成功'),
        ),
        migrations.AddField(
            model_name='userloginrecord',
            name='login_type',
            field=models.CharField(blank=True, help_text='登录方式(如:password/totp/github/email-code等)', max_length=64, null=True, verbose_name='登录方式'),
        ),
        migrations.AddField(
            model_name='userloginrecord',
            name='platform',
            field=models.CharField(blank=True, help_text='如IOS/Android/Windows等', max_length=64, null=True, verbose_name='设备平台'),
        ),
        migrations.AddField(
            model_name='userloginrecord',
            name='risk_flag',
            field=models.BooleanField(default=False, verbose_name='是否为风控标记登录'),
        ),
        migrations.AlterField(
            model_name='userloginrecord',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='基于IP的地理位置'),
        ),
    ]
