# Generated by Django 5.2.2 on 2026-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_date_joined_time_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(editable=False, help_text='雪花算法生成的用户ID', primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
