# Generated by Django 5.2.2 on 2026-05-21 02:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='系统内部唯一标识', max_length=64, unique=True, verbose_name='Provider 标识')),
                ('display_name', models.CharField(blank=True, default='', help_text='后台展示名称', max_length=128, verbose_name='显示名称')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI 官方 API'), ('azure_openai', 'Azure OpenAI'), ('openai_compatible', 'OpenAI-compatible 网关')], db_index=True, default='openai', help_text='区分 OpenAI 官方、Azure OpenAI 或兼容 OpenAI 协议的网关', max_length=32, verbose_name='Provider 类型')),
                ('base_url', models.URLField(default='https://api.openai.com/v1', help_text='API 基础地址, 不包含具体 endpoint', max_length=512, verbose_name='API Base URL')),
                ('api_version', models.CharField(blank=True, default='', help_text='Azure OpenAI 常用 api-version；OpenAI 官方 API 通常留空', max_length=64, verbose_name='API Version')),
                ('api_key_secret_name', models.CharField(help_text='Azure Key Vault 中保存 API Key 的 secret 名称', max_length=128, verbose_name='API Key Secret Name')),
                ('organization_id', models.CharField(blank=True, default='', help_text='OpenAI-Organization 请求头对应的组织 ID，可选', max_length=128, verbose_name='OpenAI Organization ID')),
                ('project_id', models.CharField(blank=True, default='', help_text='OpenAI-Project 请求头对应的项目 ID, 可选', max_length=128, verbose_name='OpenAI Project ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='关闭后 service 层不得继续使用该 provider 发起调用', verbose_name='是否启用')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='默认 Provider 的唯一性由 admin/service 写操作加锁保证', verbose_name='是否默认 Provider')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, help_text='该 Provider 的 HTTP 请求超时时间，单位秒', verbose_name='请求超时时间')),
                ('max_retries', models.PositiveIntegerField(default=2, help_text='网络抖动、限流等可重试错误的最大重试次数', verbose_name='最大重试次数')),
                ('remark', models.CharField(blank=True, default='', help_text='运维备注', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OpenAI Provider 配置',
                'verbose_name_plural': 'OpenAI Provider 配置',
                'db_table': 'openai_api_provider_config',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['provider_type', 'enabled'], name='idx_oai_provider_type_enabled'), models.Index(fields=['is_default', 'enabled'], name='idx_oai_provider_default')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='实际传递给 OpenAI API 的模型名称', max_length=128, verbose_name='模型名称')),
                ('display_name', models.CharField(blank=True, default='', help_text='后台或前端展示名称(为空时默认使用模型名称)', max_length=128, verbose_name='显示名称')),
                ('api_family', models.CharField(choices=[('responses', 'Responses API'), ('chat_completions', 'Chat Completions API'), ('embeddings', 'Embeddings API'), ('images', 'Images API'), ('audio', 'Audio API'), ('realtime', 'Realtime API'), ('other', '其他')], db_index=True, default='responses', help_text='该模型默认通过哪个 OpenAI API 入口调用', max_length=32, verbose_name='API 类型')),
                ('model_category', models.CharField(choices=[('text', '文本模型'), ('reasoning', '推理模型'), ('multimodal', '多模态模型'), ('embedding', 'Embedding 模型'), ('image', '图像模型'), ('audio', '音频模型'), ('other', '其他')], db_index=True, default='text', help_text='模型能力类别, 用于前端筛选和 service 层策略判断', max_length=32, verbose_name='模型类别')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='关闭后业务模块不得继续向用户暴露或调用该模型', verbose_name='是否启用')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='默认模型唯一性由 admin/service 写操作加锁保证', verbose_name='是否默认模型')),
                ('context_window', models.PositiveIntegerField(default=0, help_text='模型最大上下文 tokens, 未知时填0', verbose_name='上下文窗口 Tokens')),
                ('max_input_tokens', models.PositiveIntegerField(default=0, help_text='后端允许的最大输入 tokens。0 表示暂不在模型层限制', verbose_name='最大输入 Tokens')),
                ('max_output_tokens', models.PositiveIntegerField(default=4096, help_text='后端允许的最大输出 tokens', verbose_name='最大输出 Tokens')),
                ('supports_stream', models.BooleanField(default=True, verbose_name='支持流式输出')),
                ('supports_tools', models.BooleanField(default=False, verbose_name='支持工具调用')),
                ('supports_json_schema', models.BooleanField(default=False, verbose_name='支持结构化输出')),
                ('supports_reasoning', models.BooleanField(default=False, help_text='是否支持 reasoning effort / reasoning tokens 等推理模型能力', verbose_name='支持推理参数')),
                ('supports_vision', models.BooleanField(default=False, help_text='是否支持图片输入或视觉理解', verbose_name='支持视觉输入')),
                ('supports_audio_input', models.BooleanField(default=False, verbose_name='支持音频输入')),
                ('supports_audio_output', models.BooleanField(default=False, verbose_name='支持音频输出')),
                ('supports_web_search', models.BooleanField(default=False, help_text='是否允许通过 Responses API 使用 web search 工具', verbose_name='支持 Web Search')),
                ('supports_file_search', models.BooleanField(default=False, help_text='是否允许通过 Responses API 使用 file search 工具', verbose_name='支持 File Search')),
                ('default_service_tier', models.CharField(choices=[('auto', 'Auto'), ('default', 'Default'), ('flex', 'Flex'), ('priority', 'Priority')], default='auto', help_text='默认请求服务层级。实际响应中的 service_tier 仍以 OpenAI 返回为准', max_length=32, verbose_name='默认服务层级')),
                ('input_price_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='输入 tokens 每 1000 tokens 的内部统计价格', max_digits=12, verbose_name='输入单价/1K Tokens')),
                ('output_price_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='输出 tokens 每 1000 tokens 的内部统计价格', max_digits=12, verbose_name='输出单价/1K Tokens')),
                ('cached_input_price_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='缓存命中输入 tokens 的内部统计价格', max_digits=12, verbose_name='缓存输入单价/1K Tokens')),
                ('currency', models.CharField(default='USD', help_text='价格字段使用的币种，仅用于内部展示和粗略统计', max_length=16, verbose_name='计价币种')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, help_text='后台或前端展示排序，数值越小越靠前', verbose_name='排序值')),
                ('remark', models.CharField(blank=True, default='', help_text='运维备注，例如使用场景、限制说明、灰度说明', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(help_text='该模型归属的 Provider。存在模型配置时禁止直接删除 Provider', on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='openai_api.openaiproviderconfig', verbose_name='所属 Provider')),
            ],
            options={
                'verbose_name': 'OpenAI 模型配置',
                'verbose_name_plural': 'OpenAI 模型配置',
                'db_table': 'openai_api_model_config',
                'ordering': ('sort_order', 'model_name'),
            },
        ),
        migrations.CreateModel(
            name='OpenAIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(db_index=True, help_text='调用发生时的 Provider 标识快照', max_length=64, verbose_name='Provider 快照')),
                ('provider_type', models.CharField(blank=True, db_index=True, default='', help_text='调用发生时的 Provider 类型快照', max_length=32, verbose_name='Provider 类型快照')),
                ('model_name', models.CharField(db_index=True, help_text='调用发生时的模型名称快照', max_length=128, verbose_name='模型名称快照')),
                ('api_operation', models.CharField(choices=[('responses', 'Responses'), ('chat_completions', 'Chat Completions'), ('embeddings', 'Embeddings'), ('images', 'Images'), ('audio', 'Audio'), ('realtime', 'Realtime'), ('other', '其他')], db_index=True, default='responses', help_text='本次调用的 OpenAI API 类型', max_length=64, verbose_name='API 操作')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '取消')], db_index=True, default='success', max_length=16, verbose_name='调用状态')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', help_text='系统内部 request_id / trace_id', max_length=128, verbose_name='内部请求 ID')),
                ('openai_request_id', models.CharField(blank=True, db_index=True, default='', help_text='OpenAI 响应头 x-request-id，用于官方支持和生产排障', max_length=128, verbose_name='OpenAI Request ID')),
                ('provider_response_id', models.CharField(blank=True, db_index=True, default='', help_text='OpenAI 返回的 resp_xxx / chatcmpl_xxx 等响应 ID', max_length=128, verbose_name='Provider 响应 ID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='业务侧幂等键。没有幂等控制时为空', max_length=128, verbose_name='幂等键')),
                ('conversation_id', models.CharField(blank=True, db_index=True, default='', help_text='MongoDB conversation 文档 ID；不保存会话正文', max_length=64, verbose_name='会话 ID')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', help_text='MongoDB conversation_message 文档 ID；不保存消息正文', max_length=64, verbose_name='消息 ID')),
                ('request_body_hash', models.CharField(blank=True, default='', help_text='请求体脱敏后的 hash，用于排障去重；不要保存 prompt 明文', max_length=128, verbose_name='请求体 Hash')),
                ('safety_identifier_hash', models.CharField(blank=True, default='', help_text='对用户安全标识做 hash 后保存，避免记录邮箱、用户名等明文', max_length=128, verbose_name='安全标识 Hash')),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Responses API 的 input_tokens；Chat Completions 的 prompt_tokens 应映射到这里', verbose_name='输入 Tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Responses API 的 output_tokens；Chat Completions 的 completion_tokens 应映射到这里', verbose_name='输出 Tokens')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='总 Tokens')),
                ('input_cached_tokens', models.PositiveIntegerField(default=0, help_text='input_tokens_details.cached_tokens 或 prompt_tokens_details.cached_tokens', verbose_name='缓存命中输入 Tokens')),
                ('input_audio_tokens', models.PositiveIntegerField(default=0, verbose_name='音频输入 Tokens')),
                ('output_audio_tokens', models.PositiveIntegerField(default=0, verbose_name='音频输出 Tokens')),
                ('output_reasoning_tokens', models.PositiveIntegerField(default=0, help_text='output_tokens_details.reasoning_tokens 或 completion_tokens_details.reasoning_tokens', verbose_name='推理 Tokens')),
                ('accepted_prediction_tokens', models.PositiveIntegerField(default=0, help_text='Predicted Outputs 命中的 tokens', verbose_name='命中预测 Tokens')),
                ('rejected_prediction_tokens', models.PositiveIntegerField(default=0, help_text='Predicted Outputs 未命中的 tokens', verbose_name='未命中预测 Tokens')),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='从 service 发起请求到收到最终响应的耗时', null=True, verbose_name='端到端耗时毫秒')),
                ('provider_processing_ms', models.PositiveIntegerField(blank=True, help_text='OpenAI 响应头 openai-processing-ms', null=True, verbose_name='Provider 处理耗时毫秒')),
                ('http_status_code', models.PositiveIntegerField(blank=True, help_text='OpenAI API 返回的 HTTP 状态码。网络错误时可为空', null=True, verbose_name='HTTP 状态码')),
                ('service_tier', models.CharField(blank=True, db_index=True, default='', help_text='OpenAI 返回的 service_tier，例如 default、flex、priority', max_length=32, verbose_name='实际服务层级')),
                ('system_fingerprint', models.CharField(blank=True, default='', help_text='后端配置指纹。兼容历史响应字段，不作为核心业务依赖', max_length=128, verbose_name='System Fingerprint')),
                ('finish_reason', models.CharField(blank=True, default='', help_text='例如 stop、length、tool_calls、content_filter', max_length=64, verbose_name='结束原因')),
                ('incomplete_reason', models.CharField(blank=True, default='', help_text='Responses API incomplete_details 或内部归一化后的不完整原因', max_length=128, verbose_name='不完整原因')),
                ('error_code', models.CharField(blank=True, db_index=True, default='', help_text='OpenAI 或系统内部错误码。成功时为空', max_length=128, verbose_name='错误码')),
                ('error_message', models.CharField(blank=True, default='', help_text='脱敏后的错误摘要，不要记录 API Key、prompt 明文或用户敏感数据', max_length=512, verbose_name='错误信息')),
                ('rate_limit_snapshot', models.JSONField(blank=True, default=dict, help_text='脱敏保存 x-ratelimit-* 响应头，便于排查限流问题', verbose_name='限流响应头快照')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='少量脱敏扩展字段，例如业务场景、租户、trace 标签', verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='调用时间')),
                ('model_config', models.ForeignKey(blank=True, help_text='本次调用使用的模型配置。模型配置删除后保留快照字段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='openai_api.openaimodelconfig', verbose_name='模型配置')),
                ('provider', models.ForeignKey(blank=True, help_text='本次调用使用的 Provider。Provider 删除后保留快照字段', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='openai_api.openaiproviderconfig', verbose_name='Provider')),
                ('user', models.ForeignKey(blank=True, help_text='发起调用的用户。用户删除后日志保留，外键置空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='调用用户')),
            ],
            options={
                'verbose_name': 'OpenAI API 调用日志',
                'verbose_name_plural': 'OpenAI API 调用日志',
                'db_table': 'openai_api_usage_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='openaimodelconfig',
            index=models.Index(fields=['api_family', 'enabled'], name='idx_oai_model_api_enabled'),
        ),
        migrations.AddIndex(
            model_name='openaimodelconfig',
            index=models.Index(fields=['model_category', 'enabled'], name='idx_oai_model_cat_enabled'),
        ),
        migrations.AddIndex(
            model_name='openaimodelconfig',
            index=models.Index(fields=['is_default', 'enabled'], name='idx_oai_model_default'),
        ),
        migrations.AddIndex(
            model_name='openaimodelconfig',
            index=models.Index(fields=['provider', 'enabled'], name='idx_oai_model_provider_enabled'),
        ),
        migrations.AddConstraint(
            model_name='openaimodelconfig',
            constraint=models.UniqueConstraint(fields=('provider', 'model_name'), name='uniq_oai_provider_model'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['user', '-created_at'], name='idx_oai_usage_user_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['model_name', '-created_at'], name='idx_oai_usage_model_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['provider_name', '-created_at'], name='idx_oai_usage_provider_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['status', '-created_at'], name='idx_oai_usage_status_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['api_operation', '-created_at'], name='idx_oai_usage_api_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['conversation_id', '-created_at'], name='idx_oai_usage_conv_time'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['message_id'], name='idx_oai_usage_message'),
        ),
        migrations.AddIndex(
            model_name='openaiusagelog',
            index=models.Index(fields=['openai_request_id'], name='idx_oai_usage_openai_req'),
        ),
    ]
